concurrency:
  cancel-in-progress: false
  group: pages
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out tag to publish
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.tag }}
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      id: pages
      name: Setup Pages
      uses: actions/configure-pages@v4
    - continue-on-error: true
      name: Build with Maven
      run: mvn -U -B -ntp clean package -DskipTests -Pdocs -Dpublish
    - continue-on-error: true
      name: Rename README.html to index.html
      run: mv dist/target/site/README.html dist/target/site/index.html
      shell: bash
    - continue-on-error: true
      name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist/target/site
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: deployment
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
name: Deploy Quickstart html to Pages
on:
  repository_dispatch:
    types: trigger-ga___publish-pages.yml
permissions:
  contents: read
  id-token: write
  pages: write
