jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      MATRIX_OS: '"ubuntu-20.04"'
      QUICKSTART_PATH: microprofile-reactive-messaging-kafka
      TEST_BOOTABLE_JAR: true
name: WildFly microprofile-reactive-messaging-kafka Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_microprofile-reactive-messaging-kafka_ci.yml
