jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: bmt
      TEST_PROVISIONED_SERVER: true
name: WildFly bmt Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_bmt_ci .yml
