jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: microprofile-jwt
      TEST_BOOTABLE_JAR: true
name: WildFly microprofile-jwt Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_microprofile-jwt_ci.yml
