jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: kitchensink
      TEST_PROVISIONED_SERVER: true
name: WildFly kitchensink Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_kitchensink_ci.yml
