jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: servlet-async
      TEST_PROVISIONED_SERVER: true
name: WildFly servlet-async Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_servlet-async_ci.yml
