jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: jta-crash-rec
      TEST_OPENSHIFT: false
name: WildFly jta-crash-rec Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_jta-crash-rec_ci.yml
