jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: jaxrs-client
      TEST_PROVISIONED_SERVER: true
name: WildFly jaxrs-client Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_jaxrs-client_ci.yml
