jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: helloworld
      TEST_PROVISIONED_SERVER: true
name: WildFly helloworld Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_helloworld_ci.yml
