jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      DEPLOYMENT_DIR: webapp
      QUICKSTART_PATH: http-custom-mechanism
      TEST_OPENSHIFT: false
      TEST_PROVISIONED_SERVER: true
name: WildFly http-custom-mechanism Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_http-custom-mechanism_ci.yml
