jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: microprofile-health
      TEST_BOOTABLE_JAR: true
name: WildFly microprofile-health Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_microprofile-health_ci.yml
