jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: numberguess
      TEST_PROVISIONED_SERVER: true
name: WildFly numberguess Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_numberguess_ci.yml
