jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: ejb-remote
      TEST_PROVISIONED_SERVER: true
name: WildFly ejb-remote Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_ejb-remote_ci.yml
