jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: jaxws-ejb
      TEST_PROVISIONED_SERVER: true
name: WildFly jaxws-ejb Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_jaxws-ejb_ci.yml
