jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: ejb-security-programmatic-auth
      TEST_OPENSHIFT: false
      TEST_PROVISIONED_SERVER: true
name: WildFly ejb-security-programmatic-auth Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_ejb-security-programmatic-auth_ci.yml
