jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: helloworld-ws
      TEST_PROVISIONED_SERVER: true
name: WildFly helloworld-ws Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_helloworld-ws_ci.yml
