jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: ee-security
      TEST_PROVISIONED_SERVER: true
name: WildFly ee-security Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_ee-security_ci.yml
