jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: microprofile-openapi
      TEST_BOOTABLE_JAR: true
name: WildFly microprofile-openapi Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_microprofile-openapi_ci.yml
