jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: microprofile-rest-client
      TEST_BOOTABLE_JAR: true
name: WildFly microprofile-rest-client Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_microprofile-rest-client_ci.yml
