jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: cmt
      TEST_PROVISIONED_SERVER: true
name: WildFly cmt Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_cmt_ci.yml
