jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      MATRIX_JDK: '"17"'
      QUICKSTART_PATH: spring-resteasy
      TEST_PROVISIONED_SERVER: true
name: WildFly spring-resteasy Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_spring-resteasy_ci.yml
