jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: helloworld-mutual-ssl-secured
      SERVER_PROVISIONING_SERVER_HOST: https://localhost:8443/
      TEST_OPENSHIFT: false
      TEST_PROVISIONED_SERVER: true
name: WildFly helloworld-mutual-ssl-secured Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_helloworld-mutual-ssl-secured_ci.yml
