jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: temperature-converter
      TEST_PROVISIONED_SERVER: true
name: WildFly temperature-converter Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_temperature-converter_ci.yml
