jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: jaxrs-jwt
      TEST_PROVISIONED_SERVER: true
name: WildFly jaxrs-jwt Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_jaxrs-jwt_ci.yml
