jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: jaxws-retail
      TEST_PROVISIONED_SERVER: true
name: WildFly jaxws-retail Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_jaxws-retail_ci.yml
