jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: hibernate
      TEST_PROVISIONED_SERVER: true
name: WildFly hibernate Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_hibernate_ci.yml
