jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      MATRIX_OS: '"ubuntu-latest"'
      QUICKSTART_PATH: mail
      TEST_OPENSHIFT: false
      TEST_PROVISIONED_SERVER: true
name: WildFly mail Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_mail_ci.yml
