jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      DEPLOYMENT_DIR: ear
      MVN_COMMAND: install
      QUICKSTART_PATH: ejb-throws-exception
      TEST_OPENSHIFT: false
      TEST_PROVISIONED_SERVER: true
name: WildFly ejb-throws-exception Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_ejb-throws-exception_ci.yml
