jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: ejb-security-context-propagation
      TEST_OPENSHIFT: false
      TEST_PROVISIONED_SERVER: true
name: WildFly ejb-security-context-propagation Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_ejb-security-context-propagation_ci.yml
