jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: microprofile-fault-tolerance
      TEST_BOOTABLE_JAR: true
name: WildFly microprofile-fault-tolerance Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_microprofile-fault-tolerance_ci.yml
