jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: micrometer
      TEST_BOOTABLE_JAR: true
      TEST_PROVISIONED_SERVER: true
name: WildFly Micrometer Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_micrometer_ci.yml
