jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: microprofile-config
      TEST_BOOTABLE_JAR: true
name: WildFly microprofile-config Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_microprofile-config_ci.yml
