jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: batch-processing
      TEST_PROVISIONED_SERVER: true
name: WildFly batch-processing Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_batch-processing_ci.yml
