jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: servlet-filterlistener
      TEST_PROVISIONED_SERVER: true
name: WildFly servlet-filterlistener Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_servlet-filterlistener_ci.yml
