jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: logging
      TEST_PROVISIONED_SERVER: true
name: WildFly logging Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_logging_ci.yml
