jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      MATRIX_OS: '"ubuntu-latest"'
      QUICKSTART_PATH: remote-helloworld-mdb
      TEST_PROVISIONED_SERVER: true
name: WildFly remote-helloworld-mdb Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_remote-helloworld-mdb_ci.yml
