jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: ejb-timer
      TEST_PROVISIONED_SERVER: true
name: WildFly ejb-timer Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_ejb-timer_ci.yml
