jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: thread-racing
      TEST_PROVISIONED_SERVER: true
name: WildFly thread-racing Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_thread-racing_ci.yml
