jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: microprofile-lra
      TEST_BOOTABLE_JAR: true
name: WildFly microprofile-lra Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_microprofile-lra_ci.yml
