jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: servlet-security
      TEST_PROVISIONED_SERVER: true
name: WildFly servlet-security Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_servlet-security_ci.yml
