jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      EXTRA_RUN_ARGS: -DPOSTGRESQL_DATABASE=todos -DPOSTGRESQL_SERVICE_HOST=localhost
        -DPOSTGRESQL_SERVICE_PORT=5432 -DPOSTGRESQL_USER=todos -DPOSTGRESQL_PASSWORD=mysecretpassword
        -DPOSTGRESQL_DATASOURCE=ToDos
      MATRIX_OS: '"ubuntu-latest"'
      QUICKSTART_PATH: todo-backend
      TEST_OPENSHIFT: true
      TEST_PROVISIONED_SERVER: true
name: WildFly todo-backend Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_todo-backend_ci.yml
