jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: websocket-endpoint
      TEST_PROVISIONED_SERVER: true
name: WildFly websocket-endpoint Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_websocket-endpoint_ci.yml
