jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: websocket-hello
      TEST_PROVISIONED_SERVER: true
name: WildFly websocket-hello Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_websocket-hello_ci.yml
