jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      DEPLOYMENT_DIR: ear
      MVN_COMMAND: install
      QUICKSTART_PATH: security-domain-to-domain
      TEST_OPENSHIFT: false
      TEST_PROVISIONED_SERVER: true
name: WildFly security-domain-to-domain Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_security-domain-to-domain_ci.yml
