jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: jts
      TEST_OPENSHIFT: false
      TEST_PROVISIONED_SERVER: false
name: WildFly jts Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_jts_ci.yml
