jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: helloworld-mdb
      TEST_PROVISIONED_SERVER: true
name: WildFly helloworld-mdb Quickstart CI
on:
  repository_dispatch:
    types: trigger-ga___quickstart_helloworld-mdb_ci.yml
